#服务
server:
  port: 8888
  ssl:
    key-store: classpath:liubinbin.top.pfx
    key-store-password: Khs0dYP4
    keyStoreType: PKCS12
  servlet:
    context-path: "/"
#Spring配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    #     新版本不支持content-type: text/html，故新写法
    servlet:
      content-type: text/html
#  resources:     #访问系统外部资源，将该目录下的文件映射到系统下
#    static-locations: classpath:/static/ #本地文件
#  mvc:
#    static-path-pattern: /pic/**
#  http:
#    multipart:
#      enable:false
# MyBatis配置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: false
    #打印sql信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志插件默认配置
zlog:
  #公司名称
  companyname: "jinghuan"
  #平台名称，必须全小写，不可以有特殊字符，请使用部门名称简写（如：ywztb）
  platformname: "tron"
  #项目名称，必须全小写，不可以有特殊字符（如：mes）
  projectname: "mdm"
  default:
    #默认索引名称，必须全小写，不可以有特殊字符
    indexname: "tenant"
    #默认日志类型，必须全小写，不可以有特殊字符（如：info、debug、warn、exception、error）
    logtype: "exception"
